### ISSUE TITLE
Proposal: Switch default branch from `master` to `main`

### ISSUE THREAD

**Issue by jazzsequence** [pantheon-deprecated/smart_content_cdn#1]
The `master` terminology is used mostly as a relic from the fact that this was originally a custom module in a Pantheon project repository. Project repositories (still) require the default branch that pushes to Pantheon to be `master` but other packages (particularly those, like this, which will be managed by Composer) don't necessarily need to follow the same rules. There's no specific reason why it _has_ to be master. The Drupal and WordPress SDK repositories, the WordPress plugin repository, and the Pantheon Edge Integrations global library all use `main` as the default branch and it would be good to standardize.

@enotick [expressed concerns](https://github.com/pantheon-systems/pantheon-edge-integrations/issues/5#issuecomment-1028293376) that we might be limited by platform expectations, but [I don't think that applies to dependency packages](https://github.com/pantheon-systems/pantheon-edge-integrations/issues/5#issuecomment-1028342845) (I will confirm).

**Comment by jazzsequence** [comment]
Perhaps @greg-1-anderson could chime in with a definitive answer?

**Comment by greg-1-anderson** [comment]
Repositories that are packaged as Composer projects may use any branch naming convention supported by Composer. dev-main => main branch is fine.
